// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using HikariNoShisai.Common.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace HikariNoShisai.DAL.CompiledModels
{
    public static class AgentTerminalUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AgentId>k__BackingField")]
        public static extern ref Guid AgentId(AgentTerminal @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Description>k__BackingField")]
        public static extern ref string Description(AgentTerminal @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsActive>k__BackingField")]
        public static extern ref bool IsActive(AgentTerminal @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(AgentTerminal @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Agent>k__BackingField")]
        public static extern ref Agent Agent(AgentTerminal @this);
    }
}
