// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using HikariNoShisai.Common.Entities;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace HikariNoShisai.DAL.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class AgentEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "HikariNoShisai.Common.Entities.Agent",
                typeof(Agent),
                baseEntityType,
                propertyCount: 5,
                navigationCount: 2,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(BaseEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetGetter(
                Guid (Agent instance) => BaseEntityUnsafeAccessors.Id(instance),
                bool (Agent instance) => BaseEntityUnsafeAccessors.Id(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetSetter(
                Agent (Agent instance, Guid value) =>
                {
                    BaseEntityUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                Agent (Agent instance, Guid value) =>
                {
                    BaseEntityUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<Guid>(0) : (entry.FlaggedAsTemporary(0) && BaseEntityUnsafeAccessors.Id(((Agent)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(0) : BaseEntityUnsafeAccessors.Id(((Agent)(entry.Entity))))),
                Guid (IInternalEntry entry) => BaseEntityUnsafeAccessors.Id(((Agent)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(id, 0),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)(entry)).ReadRelationshipSnapshotValue<Guid>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = SqliteGuidTypeMapping.Default;
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(id));

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(BaseEntity).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseEntity).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            createdAt.SetGetter(
                DateTimeOffset (Agent instance) => BaseEntityUnsafeAccessors.CreatedAt(instance),
                bool (Agent instance) => BaseEntityUnsafeAccessors.CreatedAt(instance).EqualsExact(default(DateTimeOffset)));
            createdAt.SetSetter(
                Agent (Agent instance, DateTimeOffset value) =>
                {
                    BaseEntityUnsafeAccessors.CreatedAt(instance) = value;
                    return instance;
                });
            createdAt.SetMaterializationSetter(
                Agent (Agent instance, DateTimeOffset value) =>
                {
                    BaseEntityUnsafeAccessors.CreatedAt(instance) = value;
                    return instance;
                });
            createdAt.SetAccessors(
                DateTimeOffset (IInternalEntry entry) => BaseEntityUnsafeAccessors.CreatedAt(((Agent)(entry.Entity))),
                DateTimeOffset (IInternalEntry entry) => BaseEntityUnsafeAccessors.CreatedAt(((Agent)(entry.Entity))),
                DateTimeOffset (IInternalEntry entry) => entry.ReadOriginalValue<DateTimeOffset>(createdAt, 1),
                DateTimeOffset (IInternalEntry entry) => entry.GetCurrentValue<DateTimeOffset>(createdAt));
            createdAt.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            createdAt.TypeMapping = SqliteDateTimeOffsetTypeMapping.Default;

            var description = runtimeEntityType.AddProperty(
                "Description",
                typeof(string),
                propertyInfo: typeof(Agent).GetProperty("Description", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Agent).GetField("<Description>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            description.SetGetter(
                string (Agent instance) => AgentUnsafeAccessors.Description(instance),
                bool (Agent instance) => AgentUnsafeAccessors.Description(instance) == null);
            description.SetSetter(
                Agent (Agent instance, string value) =>
                {
                    AgentUnsafeAccessors.Description(instance) = value;
                    return instance;
                });
            description.SetMaterializationSetter(
                Agent (Agent instance, string value) =>
                {
                    AgentUnsafeAccessors.Description(instance) = value;
                    return instance;
                });
            description.SetAccessors(
                string (IInternalEntry entry) => AgentUnsafeAccessors.Description(((Agent)(entry.Entity))),
                string (IInternalEntry entry) => AgentUnsafeAccessors.Description(((Agent)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(description, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(description));
            description.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            description.TypeMapping = SqliteStringTypeMapping.Default;

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(Agent).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Agent).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            name.SetGetter(
                string (Agent instance) => AgentUnsafeAccessors.Name(instance),
                bool (Agent instance) => AgentUnsafeAccessors.Name(instance) == null);
            name.SetSetter(
                Agent (Agent instance, string value) =>
                {
                    AgentUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetMaterializationSetter(
                Agent (Agent instance, string value) =>
                {
                    AgentUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetAccessors(
                string (IInternalEntry entry) => AgentUnsafeAccessors.Name(((Agent)(entry.Entity))),
                string (IInternalEntry entry) => AgentUnsafeAccessors.Name(((Agent)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(name, 3),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(name));
            name.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            name.TypeMapping = SqliteStringTypeMapping.Default;

            var updatedAt = runtimeEntityType.AddProperty(
                "UpdatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(BaseEntity).GetProperty("UpdatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseEntity).GetField("<UpdatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            updatedAt.SetGetter(
                DateTimeOffset (Agent instance) => BaseEntityUnsafeAccessors.UpdatedAt(instance),
                bool (Agent instance) => BaseEntityUnsafeAccessors.UpdatedAt(instance).EqualsExact(default(DateTimeOffset)));
            updatedAt.SetSetter(
                Agent (Agent instance, DateTimeOffset value) =>
                {
                    BaseEntityUnsafeAccessors.UpdatedAt(instance) = value;
                    return instance;
                });
            updatedAt.SetMaterializationSetter(
                Agent (Agent instance, DateTimeOffset value) =>
                {
                    BaseEntityUnsafeAccessors.UpdatedAt(instance) = value;
                    return instance;
                });
            updatedAt.SetAccessors(
                DateTimeOffset (IInternalEntry entry) => BaseEntityUnsafeAccessors.UpdatedAt(((Agent)(entry.Entity))),
                DateTimeOffset (IInternalEntry entry) => BaseEntityUnsafeAccessors.UpdatedAt(((Agent)(entry.Entity))),
                DateTimeOffset (IInternalEntry entry) => entry.ReadOriginalValue<DateTimeOffset>(updatedAt, 4),
                DateTimeOffset (IInternalEntry entry) => entry.GetCurrentValue<DateTimeOffset>(updatedAt));
            updatedAt.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            updatedAt.TypeMapping = SqliteDateTimeOffsetTypeMapping.Default;

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var createdAt = runtimeEntityType.FindProperty("CreatedAt");
            var description = runtimeEntityType.FindProperty("Description");
            var name = runtimeEntityType.FindProperty("Name");
            var updatedAt = runtimeEntityType.FindProperty("UpdatedAt");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<Guid>(key));
            var statusLogs = runtimeEntityType.FindNavigation("StatusLogs");
            var terminals = runtimeEntityType.FindNavigation("Terminals");
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((Agent)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, DateTimeOffset, string, string, DateTimeOffset>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), ((ValueComparer<DateTimeOffset>)(((IProperty)createdAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTimeOffset>(createdAt)), (source.GetCurrentValue<string>(description) == null ? null : ((ValueComparer<string>)(((IProperty)description).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(description))), (source.GetCurrentValue<string>(name) == null ? null : ((ValueComparer<string>)(((IProperty)name).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(name))), ((ValueComparer<DateTimeOffset>)(((IProperty)updatedAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTimeOffset>(updatedAt)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(default(Guid))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<Guid>(default(Guid)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((Agent)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, object, object>(((ValueComparer<Guid>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), SnapshotFactoryFactory.SnapshotCollection(source.GetCurrentValue<ICollection<AgentStatusLog>>(statusLogs)), SnapshotFactoryFactory.SnapshotCollection(source.GetCurrentValue<ICollection<AgentTerminal>>(terminals)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 5,
                navigationCount: 2,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 5,
                shadowCount: 0,
                relationshipCount: 3,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Agents");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
