// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using HikariNoShisai.Common.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;

#pragma warning disable 219, 612, 618
#nullable disable

namespace HikariNoShisai.DAL.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class AgentStatusLogEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "HikariNoShisai.Common.Entities.AgentStatusLog",
                typeof(AgentStatusLog),
                baseEntityType,
                propertyCount: 7,
                navigationCount: 1,
                foreignKeyCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(BaseEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetGetter(
                Guid (AgentStatusLog instance) => BaseEntityUnsafeAccessors.Id(instance),
                bool (AgentStatusLog instance) => BaseEntityUnsafeAccessors.Id(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetSetter(
                AgentStatusLog (AgentStatusLog instance, Guid value) =>
                {
                    BaseEntityUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                AgentStatusLog (AgentStatusLog instance, Guid value) =>
                {
                    BaseEntityUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<Guid>(0) : (entry.FlaggedAsTemporary(0) && BaseEntityUnsafeAccessors.Id(((AgentStatusLog)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(0) : BaseEntityUnsafeAccessors.Id(((AgentStatusLog)(entry.Entity))))),
                Guid (IInternalEntry entry) => BaseEntityUnsafeAccessors.Id(((AgentStatusLog)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(id, 0),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)(entry)).ReadRelationshipSnapshotValue<Guid>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = SqliteGuidTypeMapping.Default;
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(id));

            var agentId = runtimeEntityType.AddProperty(
                "AgentId",
                typeof(Guid),
                propertyInfo: typeof(AgentStatusLog).GetProperty("AgentId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AgentStatusLog).GetField("<AgentId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            agentId.SetGetter(
                Guid (AgentStatusLog instance) => AgentStatusLogUnsafeAccessors.AgentId(instance),
                bool (AgentStatusLog instance) => AgentStatusLogUnsafeAccessors.AgentId(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            agentId.SetSetter(
                AgentStatusLog (AgentStatusLog instance, Guid value) =>
                {
                    AgentStatusLogUnsafeAccessors.AgentId(instance) = value;
                    return instance;
                });
            agentId.SetMaterializationSetter(
                AgentStatusLog (AgentStatusLog instance, Guid value) =>
                {
                    AgentStatusLogUnsafeAccessors.AgentId(instance) = value;
                    return instance;
                });
            agentId.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(1) ? entry.ReadStoreGeneratedValue<Guid>(1) : (entry.FlaggedAsTemporary(1) && AgentStatusLogUnsafeAccessors.AgentId(((AgentStatusLog)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(1) : AgentStatusLogUnsafeAccessors.AgentId(((AgentStatusLog)(entry.Entity))))),
                Guid (IInternalEntry entry) => AgentStatusLogUnsafeAccessors.AgentId(((AgentStatusLog)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(agentId, 1),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)(entry)).ReadRelationshipSnapshotValue<Guid>(agentId, 1));
            agentId.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: 1);
            agentId.TypeMapping = SqliteGuidTypeMapping.Default;
            agentId.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(agentId));

            var batteryVoltage = runtimeEntityType.AddProperty(
                "BatteryVoltage",
                typeof(int),
                propertyInfo: typeof(AgentStatusLog).GetProperty("BatteryVoltage", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AgentStatusLog).GetField("<BatteryVoltage>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            batteryVoltage.SetGetter(
                int (AgentStatusLog instance) => AgentStatusLogUnsafeAccessors.BatteryVoltage(instance),
                bool (AgentStatusLog instance) => AgentStatusLogUnsafeAccessors.BatteryVoltage(instance) == 0);
            batteryVoltage.SetSetter(
                AgentStatusLog (AgentStatusLog instance, int value) =>
                {
                    AgentStatusLogUnsafeAccessors.BatteryVoltage(instance) = value;
                    return instance;
                });
            batteryVoltage.SetMaterializationSetter(
                AgentStatusLog (AgentStatusLog instance, int value) =>
                {
                    AgentStatusLogUnsafeAccessors.BatteryVoltage(instance) = value;
                    return instance;
                });
            batteryVoltage.SetAccessors(
                int (IInternalEntry entry) => AgentStatusLogUnsafeAccessors.BatteryVoltage(((AgentStatusLog)(entry.Entity))),
                int (IInternalEntry entry) => AgentStatusLogUnsafeAccessors.BatteryVoltage(((AgentStatusLog)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(batteryVoltage, 2),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(batteryVoltage));
            batteryVoltage.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            batteryVoltage.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(BaseEntity).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseEntity).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            createdAt.SetGetter(
                DateTimeOffset (AgentStatusLog instance) => BaseEntityUnsafeAccessors.CreatedAt(instance),
                bool (AgentStatusLog instance) => BaseEntityUnsafeAccessors.CreatedAt(instance).EqualsExact(default(DateTimeOffset)));
            createdAt.SetSetter(
                AgentStatusLog (AgentStatusLog instance, DateTimeOffset value) =>
                {
                    BaseEntityUnsafeAccessors.CreatedAt(instance) = value;
                    return instance;
                });
            createdAt.SetMaterializationSetter(
                AgentStatusLog (AgentStatusLog instance, DateTimeOffset value) =>
                {
                    BaseEntityUnsafeAccessors.CreatedAt(instance) = value;
                    return instance;
                });
            createdAt.SetAccessors(
                DateTimeOffset (IInternalEntry entry) => BaseEntityUnsafeAccessors.CreatedAt(((AgentStatusLog)(entry.Entity))),
                DateTimeOffset (IInternalEntry entry) => BaseEntityUnsafeAccessors.CreatedAt(((AgentStatusLog)(entry.Entity))),
                DateTimeOffset (IInternalEntry entry) => entry.ReadOriginalValue<DateTimeOffset>(createdAt, 3),
                DateTimeOffset (IInternalEntry entry) => entry.GetCurrentValue<DateTimeOffset>(createdAt));
            createdAt.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            createdAt.TypeMapping = SqliteDateTimeOffsetTypeMapping.Default;

            var gridVoltage = runtimeEntityType.AddProperty(
                "GridVoltage",
                typeof(int),
                propertyInfo: typeof(AgentStatusLog).GetProperty("GridVoltage", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AgentStatusLog).GetField("<GridVoltage>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            gridVoltage.SetGetter(
                int (AgentStatusLog instance) => AgentStatusLogUnsafeAccessors.GridVoltage(instance),
                bool (AgentStatusLog instance) => AgentStatusLogUnsafeAccessors.GridVoltage(instance) == 0);
            gridVoltage.SetSetter(
                AgentStatusLog (AgentStatusLog instance, int value) =>
                {
                    AgentStatusLogUnsafeAccessors.GridVoltage(instance) = value;
                    return instance;
                });
            gridVoltage.SetMaterializationSetter(
                AgentStatusLog (AgentStatusLog instance, int value) =>
                {
                    AgentStatusLogUnsafeAccessors.GridVoltage(instance) = value;
                    return instance;
                });
            gridVoltage.SetAccessors(
                int (IInternalEntry entry) => AgentStatusLogUnsafeAccessors.GridVoltage(((AgentStatusLog)(entry.Entity))),
                int (IInternalEntry entry) => AgentStatusLogUnsafeAccessors.GridVoltage(((AgentStatusLog)(entry.Entity))),
                int (IInternalEntry entry) => entry.ReadOriginalValue<int>(gridVoltage, 4),
                int (IInternalEntry entry) => entry.GetCurrentValue<int>(gridVoltage));
            gridVoltage.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            gridVoltage.TypeMapping = IntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                keyComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    bool (int v1, int v2) => v1 == v2,
                    int (int v) => v,
                    int (int v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var isGridAvailable = runtimeEntityType.AddProperty(
                "IsGridAvailable",
                typeof(bool),
                propertyInfo: typeof(AgentStatusLog).GetProperty("IsGridAvailable", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AgentStatusLog).GetField("<IsGridAvailable>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            isGridAvailable.SetGetter(
                bool (AgentStatusLog instance) => AgentStatusLogUnsafeAccessors.IsGridAvailable(instance),
                bool (AgentStatusLog instance) => AgentStatusLogUnsafeAccessors.IsGridAvailable(instance) == false);
            isGridAvailable.SetSetter(
                AgentStatusLog (AgentStatusLog instance, bool value) =>
                {
                    AgentStatusLogUnsafeAccessors.IsGridAvailable(instance) = value;
                    return instance;
                });
            isGridAvailable.SetMaterializationSetter(
                AgentStatusLog (AgentStatusLog instance, bool value) =>
                {
                    AgentStatusLogUnsafeAccessors.IsGridAvailable(instance) = value;
                    return instance;
                });
            isGridAvailable.SetAccessors(
                bool (IInternalEntry entry) => AgentStatusLogUnsafeAccessors.IsGridAvailable(((AgentStatusLog)(entry.Entity))),
                bool (IInternalEntry entry) => AgentStatusLogUnsafeAccessors.IsGridAvailable(((AgentStatusLog)(entry.Entity))),
                bool (IInternalEntry entry) => entry.ReadOriginalValue<bool>(isGridAvailable, 5),
                bool (IInternalEntry entry) => entry.GetCurrentValue<bool>(isGridAvailable));
            isGridAvailable.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            isGridAvailable.TypeMapping = BoolTypeMapping.Default.Clone(
                comparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                keyComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                providerValueComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var updatedAt = runtimeEntityType.AddProperty(
                "UpdatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(BaseEntity).GetProperty("UpdatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseEntity).GetField("<UpdatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            updatedAt.SetGetter(
                DateTimeOffset (AgentStatusLog instance) => BaseEntityUnsafeAccessors.UpdatedAt(instance),
                bool (AgentStatusLog instance) => BaseEntityUnsafeAccessors.UpdatedAt(instance).EqualsExact(default(DateTimeOffset)));
            updatedAt.SetSetter(
                AgentStatusLog (AgentStatusLog instance, DateTimeOffset value) =>
                {
                    BaseEntityUnsafeAccessors.UpdatedAt(instance) = value;
                    return instance;
                });
            updatedAt.SetMaterializationSetter(
                AgentStatusLog (AgentStatusLog instance, DateTimeOffset value) =>
                {
                    BaseEntityUnsafeAccessors.UpdatedAt(instance) = value;
                    return instance;
                });
            updatedAt.SetAccessors(
                DateTimeOffset (IInternalEntry entry) => BaseEntityUnsafeAccessors.UpdatedAt(((AgentStatusLog)(entry.Entity))),
                DateTimeOffset (IInternalEntry entry) => BaseEntityUnsafeAccessors.UpdatedAt(((AgentStatusLog)(entry.Entity))),
                DateTimeOffset (IInternalEntry entry) => entry.ReadOriginalValue<DateTimeOffset>(updatedAt, 6),
                DateTimeOffset (IInternalEntry entry) => entry.GetCurrentValue<DateTimeOffset>(updatedAt));
            updatedAt.SetPropertyIndexes(
                index: 6,
                originalValueIndex: 6,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            updatedAt.TypeMapping = SqliteDateTimeOffsetTypeMapping.Default;

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { agentId });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("AgentId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            var agent = declaringEntityType.AddNavigation("Agent",
                runtimeForeignKey,
                onDependent: true,
                typeof(Agent),
                propertyInfo: typeof(AgentStatusLog).GetProperty("Agent", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AgentStatusLog).GetField("<Agent>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            agent.SetGetter(
                Agent (AgentStatusLog instance) => AgentStatusLogUnsafeAccessors.Agent(instance),
                bool (AgentStatusLog instance) => AgentStatusLogUnsafeAccessors.Agent(instance) == null);
            agent.SetSetter(
                AgentStatusLog (AgentStatusLog instance, Agent value) =>
                {
                    AgentStatusLogUnsafeAccessors.Agent(instance) = value;
                    return instance;
                });
            agent.SetMaterializationSetter(
                AgentStatusLog (AgentStatusLog instance, Agent value) =>
                {
                    AgentStatusLogUnsafeAccessors.Agent(instance) = value;
                    return instance;
                });
            agent.SetAccessors(
                Agent (IInternalEntry entry) => AgentStatusLogUnsafeAccessors.Agent(((AgentStatusLog)(entry.Entity))),
                Agent (IInternalEntry entry) => AgentStatusLogUnsafeAccessors.Agent(((AgentStatusLog)(entry.Entity))),
                null,
                Agent (IInternalEntry entry) => entry.GetCurrentValue<Agent>(agent));
            agent.SetPropertyIndexes(
                index: 0,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 2,
                storeGenerationIndex: -1);
            var statusLogs = principalEntityType.AddNavigation("StatusLogs",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<AgentStatusLog>),
                propertyInfo: typeof(Agent).GetProperty("StatusLogs", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Agent).GetField("<StatusLogs>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            statusLogs.SetGetter(
                ICollection<AgentStatusLog> (Agent instance) => AgentUnsafeAccessors.StatusLogs(instance),
                bool (Agent instance) => AgentUnsafeAccessors.StatusLogs(instance) == null);
            statusLogs.SetSetter(
                Agent (Agent instance, ICollection<AgentStatusLog> value) =>
                {
                    AgentUnsafeAccessors.StatusLogs(instance) = value;
                    return instance;
                });
            statusLogs.SetMaterializationSetter(
                Agent (Agent instance, ICollection<AgentStatusLog> value) =>
                {
                    AgentUnsafeAccessors.StatusLogs(instance) = value;
                    return instance;
                });
            statusLogs.SetAccessors(
                ICollection<AgentStatusLog> (IInternalEntry entry) => AgentUnsafeAccessors.StatusLogs(((Agent)(entry.Entity))),
                ICollection<AgentStatusLog> (IInternalEntry entry) => AgentUnsafeAccessors.StatusLogs(((Agent)(entry.Entity))),
                null,
                ICollection<AgentStatusLog> (IInternalEntry entry) => entry.GetCurrentValue<ICollection<AgentStatusLog>>(statusLogs));
            statusLogs.SetPropertyIndexes(
                index: 0,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: -1);
            statusLogs.SetCollectionAccessor<Agent, ICollection<AgentStatusLog>, AgentStatusLog>(
                ICollection<AgentStatusLog> (Agent entity) => AgentUnsafeAccessors.StatusLogs(entity),
                (Agent entity, ICollection<AgentStatusLog> collection) => AgentUnsafeAccessors.StatusLogs(entity) = ((ICollection<AgentStatusLog>)(collection)),
                (Agent entity, ICollection<AgentStatusLog> collection) => AgentUnsafeAccessors.StatusLogs(entity) = ((ICollection<AgentStatusLog>)(collection)),
                ICollection<AgentStatusLog> (Agent entity, Action<Agent, ICollection<AgentStatusLog>> setter) => ClrCollectionAccessorFactory.CreateAndSetHashSet<Agent, ICollection<AgentStatusLog>, AgentStatusLog>(entity, setter),
                ICollection<AgentStatusLog> () => ((ICollection<AgentStatusLog>)(((ICollection<AgentStatusLog>)(new HashSet<AgentStatusLog>(ReferenceEqualityComparer.Instance))))));
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var agentId = runtimeEntityType.FindProperty("AgentId");
            var batteryVoltage = runtimeEntityType.FindProperty("BatteryVoltage");
            var createdAt = runtimeEntityType.FindProperty("CreatedAt");
            var gridVoltage = runtimeEntityType.FindProperty("GridVoltage");
            var isGridAvailable = runtimeEntityType.FindProperty("IsGridAvailable");
            var updatedAt = runtimeEntityType.FindProperty("UpdatedAt");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<Guid>(key));
            var agent = runtimeEntityType.FindNavigation("Agent");
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((AgentStatusLog)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, Guid, int, DateTimeOffset, int, bool, DateTimeOffset>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), ((ValueComparer<Guid>)(((IProperty)agentId).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(agentId)), ((ValueComparer<int>)(((IProperty)batteryVoltage).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(batteryVoltage)), ((ValueComparer<DateTimeOffset>)(((IProperty)createdAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTimeOffset>(createdAt)), ((ValueComparer<int>)(((IProperty)gridVoltage).GetValueComparer())).Snapshot(source.GetCurrentValue<int>(gridVoltage)), ((ValueComparer<bool>)(((IProperty)isGridAvailable).GetValueComparer())).Snapshot(source.GetCurrentValue<bool>(isGridAvailable)), ((ValueComparer<DateTimeOffset>)(((IProperty)updatedAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTimeOffset>(updatedAt)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid, Guid>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(default(Guid)), ((ValueComparer<Guid>)(((IProperty)agentId).GetValueComparer())).Snapshot(default(Guid))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<Guid, Guid>(default(Guid), default(Guid)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((AgentStatusLog)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, Guid, object>(((ValueComparer<Guid>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), ((ValueComparer<Guid>)(((IProperty)agentId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(agentId)), source.GetCurrentValue<Agent>(agent))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 7,
                navigationCount: 1,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 7,
                shadowCount: 0,
                relationshipCount: 3,
                storeGeneratedCount: 2));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "AgentStatusLogs");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
