// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using HikariNoShisai.Common.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;

#pragma warning disable 219, 612, 618
#nullable disable

namespace HikariNoShisai.DAL.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class AgentTerminalEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "HikariNoShisai.Common.Entities.AgentTerminal",
                typeof(AgentTerminal),
                baseEntityType,
                propertyCount: 7,
                navigationCount: 1,
                foreignKeyCount: 1,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(BaseEntity).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseEntity).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetGetter(
                Guid (AgentTerminal instance) => BaseEntityUnsafeAccessors.Id(instance),
                bool (AgentTerminal instance) => BaseEntityUnsafeAccessors.Id(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetSetter(
                AgentTerminal (AgentTerminal instance, Guid value) =>
                {
                    BaseEntityUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                AgentTerminal (AgentTerminal instance, Guid value) =>
                {
                    BaseEntityUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<Guid>(0) : (entry.FlaggedAsTemporary(0) && BaseEntityUnsafeAccessors.Id(((AgentTerminal)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(0) : BaseEntityUnsafeAccessors.Id(((AgentTerminal)(entry.Entity))))),
                Guid (IInternalEntry entry) => BaseEntityUnsafeAccessors.Id(((AgentTerminal)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(id, 0),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)(entry)).ReadRelationshipSnapshotValue<Guid>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = SqliteGuidTypeMapping.Default;
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(id));

            var agentId = runtimeEntityType.AddProperty(
                "AgentId",
                typeof(Guid),
                propertyInfo: typeof(AgentTerminal).GetProperty("AgentId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AgentTerminal).GetField("<AgentId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            agentId.SetGetter(
                Guid (AgentTerminal instance) => AgentTerminalUnsafeAccessors.AgentId(instance),
                bool (AgentTerminal instance) => AgentTerminalUnsafeAccessors.AgentId(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            agentId.SetSetter(
                AgentTerminal (AgentTerminal instance, Guid value) =>
                {
                    AgentTerminalUnsafeAccessors.AgentId(instance) = value;
                    return instance;
                });
            agentId.SetMaterializationSetter(
                AgentTerminal (AgentTerminal instance, Guid value) =>
                {
                    AgentTerminalUnsafeAccessors.AgentId(instance) = value;
                    return instance;
                });
            agentId.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(1) ? entry.ReadStoreGeneratedValue<Guid>(1) : (entry.FlaggedAsTemporary(1) && AgentTerminalUnsafeAccessors.AgentId(((AgentTerminal)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(1) : AgentTerminalUnsafeAccessors.AgentId(((AgentTerminal)(entry.Entity))))),
                Guid (IInternalEntry entry) => AgentTerminalUnsafeAccessors.AgentId(((AgentTerminal)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(agentId, 1),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)(entry)).ReadRelationshipSnapshotValue<Guid>(agentId, 1));
            agentId.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: 1,
                storeGenerationIndex: 1);
            agentId.TypeMapping = SqliteGuidTypeMapping.Default;
            agentId.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(agentId));

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(BaseEntity).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseEntity).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            createdAt.SetGetter(
                DateTimeOffset (AgentTerminal instance) => BaseEntityUnsafeAccessors.CreatedAt(instance),
                bool (AgentTerminal instance) => BaseEntityUnsafeAccessors.CreatedAt(instance).EqualsExact(default(DateTimeOffset)));
            createdAt.SetSetter(
                AgentTerminal (AgentTerminal instance, DateTimeOffset value) =>
                {
                    BaseEntityUnsafeAccessors.CreatedAt(instance) = value;
                    return instance;
                });
            createdAt.SetMaterializationSetter(
                AgentTerminal (AgentTerminal instance, DateTimeOffset value) =>
                {
                    BaseEntityUnsafeAccessors.CreatedAt(instance) = value;
                    return instance;
                });
            createdAt.SetAccessors(
                DateTimeOffset (IInternalEntry entry) => BaseEntityUnsafeAccessors.CreatedAt(((AgentTerminal)(entry.Entity))),
                DateTimeOffset (IInternalEntry entry) => BaseEntityUnsafeAccessors.CreatedAt(((AgentTerminal)(entry.Entity))),
                DateTimeOffset (IInternalEntry entry) => entry.ReadOriginalValue<DateTimeOffset>(createdAt, 2),
                DateTimeOffset (IInternalEntry entry) => entry.GetCurrentValue<DateTimeOffset>(createdAt));
            createdAt.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            createdAt.TypeMapping = SqliteDateTimeOffsetTypeMapping.Default;

            var description = runtimeEntityType.AddProperty(
                "Description",
                typeof(string),
                propertyInfo: typeof(AgentTerminal).GetProperty("Description", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AgentTerminal).GetField("<Description>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            description.SetGetter(
                string (AgentTerminal instance) => AgentTerminalUnsafeAccessors.Description(instance),
                bool (AgentTerminal instance) => AgentTerminalUnsafeAccessors.Description(instance) == null);
            description.SetSetter(
                AgentTerminal (AgentTerminal instance, string value) =>
                {
                    AgentTerminalUnsafeAccessors.Description(instance) = value;
                    return instance;
                });
            description.SetMaterializationSetter(
                AgentTerminal (AgentTerminal instance, string value) =>
                {
                    AgentTerminalUnsafeAccessors.Description(instance) = value;
                    return instance;
                });
            description.SetAccessors(
                string (IInternalEntry entry) => AgentTerminalUnsafeAccessors.Description(((AgentTerminal)(entry.Entity))),
                string (IInternalEntry entry) => AgentTerminalUnsafeAccessors.Description(((AgentTerminal)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(description, 3),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(description));
            description.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            description.TypeMapping = SqliteStringTypeMapping.Default;

            var isActive = runtimeEntityType.AddProperty(
                "IsActive",
                typeof(bool),
                propertyInfo: typeof(AgentTerminal).GetProperty("IsActive", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AgentTerminal).GetField("<IsActive>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            isActive.SetGetter(
                bool (AgentTerminal instance) => AgentTerminalUnsafeAccessors.IsActive(instance),
                bool (AgentTerminal instance) => AgentTerminalUnsafeAccessors.IsActive(instance) == false);
            isActive.SetSetter(
                AgentTerminal (AgentTerminal instance, bool value) =>
                {
                    AgentTerminalUnsafeAccessors.IsActive(instance) = value;
                    return instance;
                });
            isActive.SetMaterializationSetter(
                AgentTerminal (AgentTerminal instance, bool value) =>
                {
                    AgentTerminalUnsafeAccessors.IsActive(instance) = value;
                    return instance;
                });
            isActive.SetAccessors(
                bool (IInternalEntry entry) => AgentTerminalUnsafeAccessors.IsActive(((AgentTerminal)(entry.Entity))),
                bool (IInternalEntry entry) => AgentTerminalUnsafeAccessors.IsActive(((AgentTerminal)(entry.Entity))),
                bool (IInternalEntry entry) => entry.ReadOriginalValue<bool>(isActive, 4),
                bool (IInternalEntry entry) => entry.GetCurrentValue<bool>(isActive));
            isActive.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            isActive.TypeMapping = BoolTypeMapping.Default.Clone(
                comparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                keyComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                providerValueComparer: new ValueComparer<bool>(
                    bool (bool v1, bool v2) => v1 == v2,
                    int (bool v) => ((object)v).GetHashCode(),
                    bool (bool v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(AgentTerminal).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AgentTerminal).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            name.SetGetter(
                string (AgentTerminal instance) => AgentTerminalUnsafeAccessors.Name(instance),
                bool (AgentTerminal instance) => AgentTerminalUnsafeAccessors.Name(instance) == null);
            name.SetSetter(
                AgentTerminal (AgentTerminal instance, string value) =>
                {
                    AgentTerminalUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetMaterializationSetter(
                AgentTerminal (AgentTerminal instance, string value) =>
                {
                    AgentTerminalUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetAccessors(
                string (IInternalEntry entry) => AgentTerminalUnsafeAccessors.Name(((AgentTerminal)(entry.Entity))),
                string (IInternalEntry entry) => AgentTerminalUnsafeAccessors.Name(((AgentTerminal)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(name, 5),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(name));
            name.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            name.TypeMapping = SqliteStringTypeMapping.Default;

            var updatedAt = runtimeEntityType.AddProperty(
                "UpdatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(BaseEntity).GetProperty("UpdatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(BaseEntity).GetField("<UpdatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            updatedAt.SetGetter(
                DateTimeOffset (AgentTerminal instance) => BaseEntityUnsafeAccessors.UpdatedAt(instance),
                bool (AgentTerminal instance) => BaseEntityUnsafeAccessors.UpdatedAt(instance).EqualsExact(default(DateTimeOffset)));
            updatedAt.SetSetter(
                AgentTerminal (AgentTerminal instance, DateTimeOffset value) =>
                {
                    BaseEntityUnsafeAccessors.UpdatedAt(instance) = value;
                    return instance;
                });
            updatedAt.SetMaterializationSetter(
                AgentTerminal (AgentTerminal instance, DateTimeOffset value) =>
                {
                    BaseEntityUnsafeAccessors.UpdatedAt(instance) = value;
                    return instance;
                });
            updatedAt.SetAccessors(
                DateTimeOffset (IInternalEntry entry) => BaseEntityUnsafeAccessors.UpdatedAt(((AgentTerminal)(entry.Entity))),
                DateTimeOffset (IInternalEntry entry) => BaseEntityUnsafeAccessors.UpdatedAt(((AgentTerminal)(entry.Entity))),
                DateTimeOffset (IInternalEntry entry) => entry.ReadOriginalValue<DateTimeOffset>(updatedAt, 6),
                DateTimeOffset (IInternalEntry entry) => entry.GetCurrentValue<DateTimeOffset>(updatedAt));
            updatedAt.SetPropertyIndexes(
                index: 6,
                originalValueIndex: 6,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            updatedAt.TypeMapping = SqliteDateTimeOffsetTypeMapping.Default;

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { agentId });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("AgentId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            var agent = declaringEntityType.AddNavigation("Agent",
                runtimeForeignKey,
                onDependent: true,
                typeof(Agent),
                propertyInfo: typeof(AgentTerminal).GetProperty("Agent", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AgentTerminal).GetField("<Agent>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            agent.SetGetter(
                Agent (AgentTerminal instance) => AgentTerminalUnsafeAccessors.Agent(instance),
                bool (AgentTerminal instance) => AgentTerminalUnsafeAccessors.Agent(instance) == null);
            agent.SetSetter(
                AgentTerminal (AgentTerminal instance, Agent value) =>
                {
                    AgentTerminalUnsafeAccessors.Agent(instance) = value;
                    return instance;
                });
            agent.SetMaterializationSetter(
                AgentTerminal (AgentTerminal instance, Agent value) =>
                {
                    AgentTerminalUnsafeAccessors.Agent(instance) = value;
                    return instance;
                });
            agent.SetAccessors(
                Agent (IInternalEntry entry) => AgentTerminalUnsafeAccessors.Agent(((AgentTerminal)(entry.Entity))),
                Agent (IInternalEntry entry) => AgentTerminalUnsafeAccessors.Agent(((AgentTerminal)(entry.Entity))),
                null,
                Agent (IInternalEntry entry) => entry.GetCurrentValue<Agent>(agent));
            agent.SetPropertyIndexes(
                index: 0,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 2,
                storeGenerationIndex: -1);
            var terminals = principalEntityType.AddNavigation("Terminals",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<AgentTerminal>),
                propertyInfo: typeof(Agent).GetProperty("Terminals", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Agent).GetField("<Terminals>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            terminals.SetGetter(
                ICollection<AgentTerminal> (Agent instance) => AgentUnsafeAccessors.Terminals(instance),
                bool (Agent instance) => AgentUnsafeAccessors.Terminals(instance) == null);
            terminals.SetSetter(
                Agent (Agent instance, ICollection<AgentTerminal> value) =>
                {
                    AgentUnsafeAccessors.Terminals(instance) = value;
                    return instance;
                });
            terminals.SetMaterializationSetter(
                Agent (Agent instance, ICollection<AgentTerminal> value) =>
                {
                    AgentUnsafeAccessors.Terminals(instance) = value;
                    return instance;
                });
            terminals.SetAccessors(
                ICollection<AgentTerminal> (IInternalEntry entry) => AgentUnsafeAccessors.Terminals(((Agent)(entry.Entity))),
                ICollection<AgentTerminal> (IInternalEntry entry) => AgentUnsafeAccessors.Terminals(((Agent)(entry.Entity))),
                null,
                ICollection<AgentTerminal> (IInternalEntry entry) => entry.GetCurrentValue<ICollection<AgentTerminal>>(terminals));
            terminals.SetPropertyIndexes(
                index: 1,
                originalValueIndex: -1,
                shadowIndex: -1,
                relationshipIndex: 2,
                storeGenerationIndex: -1);
            terminals.SetCollectionAccessor<Agent, ICollection<AgentTerminal>, AgentTerminal>(
                ICollection<AgentTerminal> (Agent entity) => AgentUnsafeAccessors.Terminals(entity),
                (Agent entity, ICollection<AgentTerminal> collection) => AgentUnsafeAccessors.Terminals(entity) = ((ICollection<AgentTerminal>)(collection)),
                (Agent entity, ICollection<AgentTerminal> collection) => AgentUnsafeAccessors.Terminals(entity) = ((ICollection<AgentTerminal>)(collection)),
                ICollection<AgentTerminal> (Agent entity, Action<Agent, ICollection<AgentTerminal>> setter) => ClrCollectionAccessorFactory.CreateAndSetHashSet<Agent, ICollection<AgentTerminal>, AgentTerminal>(entity, setter),
                ICollection<AgentTerminal> () => ((ICollection<AgentTerminal>)(((ICollection<AgentTerminal>)(new HashSet<AgentTerminal>(ReferenceEqualityComparer.Instance))))));
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var agentId = runtimeEntityType.FindProperty("AgentId");
            var createdAt = runtimeEntityType.FindProperty("CreatedAt");
            var description = runtimeEntityType.FindProperty("Description");
            var isActive = runtimeEntityType.FindProperty("IsActive");
            var name = runtimeEntityType.FindProperty("Name");
            var updatedAt = runtimeEntityType.FindProperty("UpdatedAt");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<Guid>(key));
            var agent = runtimeEntityType.FindNavigation("Agent");
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((AgentTerminal)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, Guid, DateTimeOffset, string, bool, string, DateTimeOffset>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), ((ValueComparer<Guid>)(((IProperty)agentId).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(agentId)), ((ValueComparer<DateTimeOffset>)(((IProperty)createdAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTimeOffset>(createdAt)), (source.GetCurrentValue<string>(description) == null ? null : ((ValueComparer<string>)(((IProperty)description).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(description))), ((ValueComparer<bool>)(((IProperty)isActive).GetValueComparer())).Snapshot(source.GetCurrentValue<bool>(isActive)), (source.GetCurrentValue<string>(name) == null ? null : ((ValueComparer<string>)(((IProperty)name).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(name))), ((ValueComparer<DateTimeOffset>)(((IProperty)updatedAt).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTimeOffset>(updatedAt)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid, Guid>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(default(Guid)), ((ValueComparer<Guid>)(((IProperty)agentId).GetValueComparer())).Snapshot(default(Guid))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<Guid, Guid>(default(Guid), default(Guid)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((AgentTerminal)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, Guid, object>(((ValueComparer<Guid>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), ((ValueComparer<Guid>)(((IProperty)agentId).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(agentId)), source.GetCurrentValue<Agent>(agent))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 7,
                navigationCount: 1,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 7,
                shadowCount: 0,
                relationshipCount: 3,
                storeGeneratedCount: 2));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "AgentTerminals");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
