// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using HikariNoShisai.Common.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace HikariNoShisai.DAL.CompiledModels
{
    public static class AgentUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Description>k__BackingField")]
        public static extern ref string Description(Agent @this);
    }
}
