// <auto-generated />
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using HikariNoShisai.Common.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace HikariNoShisai.DAL.CompiledModels
{
    public static class AgentUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Description>k__BackingField")]
        public static extern ref string Description(Agent @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(Agent @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<StatusLogs>k__BackingField")]
        public static extern ref ICollection<AgentStatusLog> StatusLogs(Agent @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Terminals>k__BackingField")]
        public static extern ref ICollection<AgentTerminal> Terminals(Agent @this);
    }
}
