// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using HikariNoShisai.Common.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace HikariNoShisai.DAL.CompiledModels
{
    public static class AgentStatusLogUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<AgentId>k__BackingField")]
        public static extern ref Guid AgentId(AgentStatusLog @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<BatteryVoltage>k__BackingField")]
        public static extern ref int BatteryVoltage(AgentStatusLog @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<GridVoltage>k__BackingField")]
        public static extern ref int GridVoltage(AgentStatusLog @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsGridAvailable>k__BackingField")]
        public static extern ref bool IsGridAvailable(AgentStatusLog @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Agent>k__BackingField")]
        public static extern ref Agent Agent(AgentStatusLog @this);
    }
}
