// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Update.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace HikariNoShisai.DAL.CompiledModels
{
    public partial class HikariNoShisaiContextModel
    {
        private HikariNoShisaiContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("930f6211-4466-4e8b-bb84-654fc5e6fb22"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var agent = AgentEntityType.Create(this);

            AgentEntityType.CreateAnnotations(agent);

            AddAnnotation("ProductVersion", "10.0.0");
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var agent = FindEntityType("HikariNoShisai.Common.Entities.Agent")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            agent.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var hikariNoShisaiCommonEntitiesAgentTableBase = new TableBase("HikariNoShisai.Common.Entities.Agent", null, relationalModel);
            var createdAtColumnBase = new ColumnBase<ColumnMappingBase>("CreatedAt", "TEXT", hikariNoShisaiCommonEntitiesAgentTableBase);
            hikariNoShisaiCommonEntitiesAgentTableBase.Columns.Add("CreatedAt", createdAtColumnBase);
            var descriptionColumnBase = new ColumnBase<ColumnMappingBase>("Description", "TEXT", hikariNoShisaiCommonEntitiesAgentTableBase);
            hikariNoShisaiCommonEntitiesAgentTableBase.Columns.Add("Description", descriptionColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "TEXT", hikariNoShisaiCommonEntitiesAgentTableBase);
            hikariNoShisaiCommonEntitiesAgentTableBase.Columns.Add("Id", idColumnBase);
            var updatedAtColumnBase = new ColumnBase<ColumnMappingBase>("UpdatedAt", "TEXT", hikariNoShisaiCommonEntitiesAgentTableBase);
            hikariNoShisaiCommonEntitiesAgentTableBase.Columns.Add("UpdatedAt", updatedAtColumnBase);
            relationalModel.DefaultTables.Add("HikariNoShisai.Common.Entities.Agent", hikariNoShisaiCommonEntitiesAgentTableBase);
            var hikariNoShisaiCommonEntitiesAgentMappingBase = new TableMappingBase<ColumnMappingBase>(agent, hikariNoShisaiCommonEntitiesAgentTableBase, null);
            hikariNoShisaiCommonEntitiesAgentTableBase.AddTypeMapping(hikariNoShisaiCommonEntitiesAgentMappingBase, false);
            defaultTableMappings.Add(hikariNoShisaiCommonEntitiesAgentMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, agent.FindProperty("Id")!, hikariNoShisaiCommonEntitiesAgentMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)createdAtColumnBase, agent.FindProperty("CreatedAt")!, hikariNoShisaiCommonEntitiesAgentMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)descriptionColumnBase, agent.FindProperty("Description")!, hikariNoShisaiCommonEntitiesAgentMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)updatedAtColumnBase, agent.FindProperty("UpdatedAt")!, hikariNoShisaiCommonEntitiesAgentMappingBase);

            var tableMappings = new List<TableMapping>();
            agent.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var agentsTable = new Table("Agents", null, relationalModel);
            var idColumn = new Column("Id", "TEXT", agentsTable);
            agentsTable.Columns.Add("Id", idColumn);
            idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(idColumn);
            var createdAtColumn = new Column("CreatedAt", "TEXT", agentsTable);
            agentsTable.Columns.Add("CreatedAt", createdAtColumn);
            createdAtColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTimeOffset>(createdAtColumn);
            var descriptionColumn = new Column("Description", "TEXT", agentsTable);
            agentsTable.Columns.Add("Description", descriptionColumn);
            descriptionColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(descriptionColumn);
            var updatedAtColumn = new Column("UpdatedAt", "TEXT", agentsTable);
            agentsTable.Columns.Add("UpdatedAt", updatedAtColumn);
            updatedAtColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTimeOffset>(updatedAtColumn);
            relationalModel.Tables.Add(("Agents", null), agentsTable);
            var agentsTableMapping = new TableMapping(agent, agentsTable, null);
            agentsTable.AddTypeMapping(agentsTableMapping, false);
            tableMappings.Add(agentsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, agent.FindProperty("Id")!, agentsTableMapping);
            RelationalModel.CreateColumnMapping(createdAtColumn, agent.FindProperty("CreatedAt")!, agentsTableMapping);
            RelationalModel.CreateColumnMapping(descriptionColumn, agent.FindProperty("Description")!, agentsTableMapping);
            RelationalModel.CreateColumnMapping(updatedAtColumn, agent.FindProperty("UpdatedAt")!, agentsTableMapping);
            var pK_Agents = new UniqueConstraint("PK_Agents", agentsTable, new[] { idColumn });
            agentsTable.PrimaryKey = pK_Agents;
            pK_Agents.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<Guid>(pK_Agents));
            var pK_AgentsKey = RelationalModel.GetKey(this,
                "HikariNoShisai.Common.Entities.Agent",
                new[] { "Id" });
            pK_Agents.MappedKeys.Add(pK_AgentsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_AgentsKey).Add(pK_Agents);
            agentsTable.UniqueConstraints.Add("PK_Agents", pK_Agents);
            return relationalModel.MakeReadOnly();
        }
    }
}
