// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace HikariNoShisai.DAL.CompiledModels
{
    public partial class HikariNoShisaiContextModel
    {
        private HikariNoShisaiContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("2813143c-7f93-468b-aec6-dece01b13b50"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var agent = AgentEntityType.Create(this);

            AgentEntityType.CreateAnnotations(agent);

            AddAnnotation("ProductVersion", "10.0.0");
        }
    }
}
