// <auto-generated />
using HikariNoShisai.DAL;
using HikariNoShisai.DAL.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(HikariNoShisaiContext), typeof(HikariNoShisaiContextModel))]
