@HikariNoShisai.WebAPI_HostAddress = http://localhost:8081

#region Agent

GET {{HikariNoShisai.WebAPI_HostAddress}}/agents/
Accept: application/json

###

GET {{HikariNoShisai.WebAPI_HostAddress}}/agents/1
Accept: application/json

###

#endregion

#region Statistics
POST {{HikariNoShisai.WebAPI_HostAddress}}/Statistics
Accept: application/json
Content-Type: application/json
x-api-key: mysupersecretkey

{
  "agentId": "00000000-0000-0000-0000-000000000001",
  "isGridAvailable": true
}

###

#endregion

#region Telegram
GET {{HikariNoShisai.WebAPI_HostAddress}}/bot//setWebhook/
Accept: application/json

###

#endregion

#region Terminal
GET {{HikariNoShisai.WebAPI_HostAddress}}/terminal?agentId=00000000-0000-0000-0000-000000000001&terminalId=00000000-0000-0000-0000-000000000002
Accept: application/json
###
PATCH {{HikariNoShisai.WebAPI_HostAddress}}/terminal?agentId=00000000-0000-0000-0000-000000000001&terminalId=00000000-0000-0000-0000-000000000002&isActive=false
Accept: application/json
###
#endregion